### ISSUE TITLE
Backsub in SLURM: Pixel size overwrite not specified (It was semicolon separator in markers.csv)

### ISSUE THREAD

**Issue by josenimo** [SchapiroLabor/Background_subtraction#20]
Dear @kbestak 

I am trying to run some samples through vanilla mcmicro and backsub is giving me some issues.

Context:
These are .czi images each about 5gb x 5 cycles. Total ashlar output about 30gb
ashlar worked perfectly, it runs into error at backsub

Problem in short:
```
Command executed:

  python3 /background_subtraction/background_sub.py   -r P30E01_Tonsil.ome.tif -m markers.csv   -o P30E01_Tonsil_backsub.ome.tif -mo markers_bs.csv

Command exit status:
  1

Command output:
  Pixel size overwrite not specified

```

Do I have to explicitly provide pixel size? 
Any clue what is going on?

P30E02_params.yml:

```
workflow:
    start-at: illumination
    stop-at: background
    background: true
    background-method: backsub

options:
    ashlar: --flip-y --align-channel 4 -m 50 --filter-sigma 1
```

nextflow script
```
#!/bin/bash
#SBATCH --job-name=P30E02_Cancer    # Job name
#SBATCH --output=P30E02.%j.out      # Output file
#SBATCH --error=P30E02.%j.err       # Error file
#SBATCH --time=24:00:00             # Time limit hrs:min:sec
#SBATCH --mem=10G                   # Memory per node
#SBATCH --cpus-per-task=2           # Number of CPU cores per task
#SBATCH --partition=medium          # Partition/queue name (check with your HPC)

eval "$(conda shell.bash hook)"
conda activate mcmicro

PATH_TO_DATA="/data/cephfs-1/home/users/jnimoca_m/work/P30_SF_HNSCC/P30E02_Cancer"
echo "Path to data: $PATH_TO_DATA"

nextflow run josenimo/mcmicro -r mcmicro_SLURM --in $PATH_TO_DATA -profile singularity --params $PATH_TO_DATA/P30E02_params.yml

echo "--end--"
```

Nextflow Standard Out:
[P30E02.10614787.log](https://github.com/user-attachments/files/17600747/P30E02.10614787.log)

Nextflow log files:
[nextflow.log](https://github.com/user-attachments/files/17600730/nextflow.log)
[nextflow1.log](https://github.com/user-attachments/files/17600731/nextflow1.log)
[nextflow2.log](https://github.com/user-attachments/files/17600732/nextflow2.log)

**Comment by josenimo** [comment]
Here you go :) 
[markers.csv](https://github.com/user-attachments/files/17601378/markers.csv)

**Comment by kbestak** [comment]
Thank you for sending it, it seems the separators in the marker file are semicolons, whereas Backsub is hardcoded to read the marker sheet as comma-separated. Could you change the marker file accordingly and just rerun Backsub on your data and let me know if the issue persists?

**Comment by josenimo** [comment]
I see, excel strikes again..
I will run this and let you know.
Thanks

**Comment by josenimo** [comment]
I confirm it works, cheers
